name: alfred_noteplan
description: Format & Refresh SQLite database for alfred-noteplan workflow
version: 2.0.1-beta.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  intl: ^0.18.0
  path: ^1.8.3
  sqlite3: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0