name: AlfredNoteplanRefresh
description: Format & Refresh SQLite database for alfred-noteplan-fts workflow
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  sqlite3: ^1.9.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0