name: alfred_noteplan_fts_refresh
description: Format & Refresh SQLite database for alfred-noteplan-fts workflow
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  alfred_workflow: ^0.3.0+1
  intl: ^0.18.0
  path: ^1.8.3
  sqlite3: ^1.9.1
  tuple: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0