name: Build Dart binaries & package Alfred Workflow

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-11, macos-12]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: dart pub get

      - name: Create the build directory
        run: mkdir build

      - name: Compile the app
        run: dart compile exe bin/aoc15.dart -o build/aoc15_${{ matrix.os }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: build/*