name: Build Dart binaries & package Alfred Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Show the architecture
        run: uname -m

      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: dart pub get

      - name: Compile the app
        run: ./r.sh build

      - name: Capture the artifact name
        run: artifact_name=`ls *.alfredworkflow | tr -d '\n'`

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.artifact_name }}